# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/time_series',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/time_series',
                'lib_path': 'time_series'},
  'syms': {'time_series.core': {'time_series.core.foo': ('core.html#foo', 'time_series/core.py')}}}
